apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tjeleh8ci-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:5ca89ba6f0235158f831b14f8dd5f65e3ac4877a@sha256:0eaf9b06c53b16c7796cdb86d51d974ccf51844dbbf81ad1adb60459e99e116b
          name: container-image
